[sophgo-config]

[devicetree]
name = sg2042-milkv-pioneer.dtb
; name = mango-sophgo-x8evb.dtb
; addr = 0x20000000

;[mac-address]
;mac0 = 0xAAAAAAAAAAAA
;mac1 = 0xAAAAAAAAAAAA

[kernel]
name = SG2042.fd
; name = riscv64_Image
; name = u-boot.bin
; name = SG2042.fd
; addr = 0x02000000

[eof]
